#ifndef CHINESEC_CPP_H
#define CHINESEC_CPP_H
#define 使用 using
#define 命名空间 namespace
#define 标准 std
#define 结构 struct
#define 类 class
#define 私有的 private
#define 公有的 public
#define 保护的 protected
#define 静态的 static
#define 友类 friend
#define 布尔型 bool
#define 正确 true
#define 错误 false
#define 主函数 main
#define 整型 int
#define 字符型 char
#define 单精度浮点型 float
#define 双精度浮点型 double
#define 无类型 void
#define 无符号 unsigned
#define 长 long
#define 短 short
#define 标准输出 cout
#define 标准输入 cin
#define 结束了 endl
#define 的 .
#define 是 =
#define 即是 =
#define 等于 ==
#define 数组 []
#define 字符串 string
#define 如果 if
#define 不然 else
#define 【 [
#define 】 ]
#define ， ,
#define 。 .
#define 《 <
#define 》 >
#define ？ ?
#define （ (
#define ） )
#define ！ !
#define —— _
#define ：： ::
#define 给左边 <<
#define 给右边 >>
#define 返回 return
#endif